let list = [
    {
      id: 1,
      title: "BOOK CHILDREN",
      genre: "Children books",
      price: 89,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/7122DVvUpDL.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "THE UNHEARD",
      genre: "Horror books",
      price: 98,
      img: "https://www.denofgeek.com/wp-content/uploads/2021/09/Books-Banner-22.png?resize=768%2C432",
      amount: 1,
    },
    {
      id: 3,
      title: "IT END WITH US",
      genre: "Love books",
      price: 143,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81s0B6NYXML.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "THE MARTIAN",
      genre: "Action books",
      price: 57,
      img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSoipuYKBmXL7pTOIducDf9T0zCFWgCrx5GwpKQCVk0xkAa78I-",
      amount: 1,
    },
    {
      id: 5,
      title: "THE CIVIL WAR",
      genre: "Marvel books",
      price: 149,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91KTnpad58L.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "AVENGER",
      genre: "Marvel books",
      price: 135,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/51f4GSVDLKL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "THE GAME OF THORNE",
      genre: "Action books",
      price: 693,
      img: "https://books.google.co.in/books/publisher/content?id=gd7UCwAAQBAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE7383U6df0OLuL9VSH35WW2zEB6OwY6V5J38OY2RyeGaSW6bPqV9nh0N1f1r7ewJ1svPq_KHiuVpGcpmmXBzCWnbdeqwM_Ph4kl4dC5Wv_hRlyZYWMOeRt3r8ulv2Qz5jVPZDHYS",
      amount: 1,
    },
    {
      id: 8,
      title: "LOVE ON THE BRAIN",
      genre: "Love books",
      price: 289,
      img: "https://images-na.ssl-images-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81XS0eEa6dL._AC_UL210_SR210,210_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "THE DEATH",
      genre: "Horror books",
      price: 80,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51Po6q6fXGL.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "CHARLOTTE",
      genre: "Children books",
      price: 86,
      img: "https://www.mkewithkids.com/wp-content/uploads/2022/03/Charlottes-Web.png",
      amount: 1,
    },
    {
      id: 11,
      title: "THE LORAX",
      genre: "Children books",
      price: 120,
      img: "https://people.com/thmb/xhZBt49ss73JTmT7CIFBiO6iA3A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(736x0:738x2)/the-lorax-book-d805a2ec02964b5cb8f6931af921ecbd.jpeg",
      amount: 1,
    },
    {
      id: 12,
      title: "STEPHEN KING",
      genre: "Horror books",
      price: 157,
      img: "https://s3.r29static.com/bin/entry/754/x,80/2030551/image.jpg",
      amount: 1,
    },
];

export default list;