let list = [
    {
      id: 1,
      title: "CHILDREN",
      genre: "Children books",
      price: 89,
      img: "https://m.media-amazon.com/images/I/51jim7NTY8L._SX331_BO1,204,203,200_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "THE UNHEARD",
      genre: "Horror books",
      price: 98,
      img: "https://www.denofgeek.com/wp-content/uploads/2021/09/Books-Banner-22.png?resize=768%2C432",
      amount: 1,
    },
    {
      id: 3,
      title: "IT END WITH US",
      genre: "Love books",
      price: 143,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81s0B6NYXML.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "THE MARTIAN",
      genre: "Action books",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81wFMY9OAFL._AC_UF1000,1000_QL80_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "THE CIVIL WAR",
      genre: "Marvel books",
      price: 149,
      img: "https://m.media-amazon.com/images/I/61p+LzYMf7L.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "AVENGER",
      genre: "Marvel books",
      price: 135,
      img:"https://cdn.kobo.com/book-images/03d149c4-7985-416f-a10d-e9f21f40dfa0/1200/1200/False/world-of-reading-avengers-these-are-the-avengers.jpg", 
      amount: 1,
    },
    {
      id: 7,
      title: "THE GAME OF THORNE",
      genre: "Action books",
      price: 693,
      img: "https://books.google.co.in/books/publisher/content?id=gd7UCwAAQBAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE7383U6df0OLuL9VSH35WW2zEB6OwY6V5J38OY2RyeGaSW6bPqV9nh0N1f1r7ewJ1svPq_KHiuVpGcpmmXBzCWnbdeqwM_Ph4kl4dC5Wv_hRlyZYWMOeRt3r8ulv2Qz5jVPZDHYS",
      amount: 1,
    },
    {
      id: 8,
      title: "LOVE ON THE BRAIN",
      genre: "Love books",
      price: 289,
      img: "https://m.media-amazon.com/images/I/71fL2RlDuAL._AC_UF1000,1000_QL80_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "THE DEATH NOTE",
      genre: "Horror books",
      price: 80,
      img: "https://cdn.kobo.com/book-images/9c781b40-1694-4f43-9e36-d946de21cb33/353/569/90/False/death-note-vol-9.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "CHARLOTTE",
      genre: "Children books",
      price: 86,
      img: "https://www.mkewithkids.com/wp-content/uploads/2022/03/Charlottes-Web.png",
      amount: 1,
    },
    {
      id: 11,
      title: "THE LORAX",
      genre: "Children books",
      price: 120,
      img: "https://people.com/thmb/xhZBt49ss73JTmT7CIFBiO6iA3A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(736x0:738x2)/the-lorax-book-d805a2ec02964b5cb8f6931af921ecbd.jpeg",
      amount: 1,
    },
    {
      id: 12,
      title: "STEPHEN KING",
      genre: "Horror books",
      price: 157,
      img: "https://s3.r29static.com/bin/entry/754/x,80/2030551/image.jpg",
      amount: 1,
    },
];

export default list;